### DISCUSSION TITLE
Chroma DB

### DISCUSSION THREAD

**Discussion by marioalexandreantunes** [oriondesign2015/SetupOrion#60] [Sugestões]
Sugestão para colocar no seu script uma base de dados de vectores que eu uso muito no Flowise. É Opensource e apesar de não ser difícil de instalação poderá um usuário comum ter dificuldades na hora de proteger com password. Creio que poderá ser importante para quem quer usar Agentes AI!

```
version: '3.7'
services:

  server:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - ANONYMIZED_TELEMETRY=False
      - IS_PERSISTENT=True
      - CHROMA_SERVER_AUTHN_CREDENTIALS=PASSWORD
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.token_authn.TokenAuthenticationServerProvider
      - CHROMA_SERVER_AUTHN_TOKEN_TRANSPORT_HEADER=X_CHROMA_TOKEN
    volumes:
      - chroma_data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - NOME_NET

volumes:
  chroma_data:
    external: true
    name: chroma_data

networks:
  NOME_NET:
    external: true
    name: NOME_NET

```

## Dicas: 

1.Não usar aspas (' "") nas environments.

2.Pode usar Autenticação simples user:password, usando ficheiro server.htpasswd
  - CHROMA_SERVER_AUTHN_CREDENTIALS_FILE=/chroma/chroma/server.htpasswd
  - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.basic_authn.BasicAuthenticationServerProvider

3. Testes com o postman e a autenticação Token que usei
  - Auth Type : Bearer e adiciona sua PASSWORD
  - Get : http://servidor.com:8000/api/v1/version
 
4.Toda a documentação da API em http://servidor.com:8000/docs
