### ISSUE TITLE
Como agregar OPEN OCR

### ISSUE THREAD

**Issue by diegonella** [oriondesign2015/SetupOrion#103]
Hola me gustaria agregar un stack con 
https://github.com/tleyden/open-ocr/tree/master

Lo he transformado a version 3.8, pero no lo puedo hacer andar, alguno me puede ayudar?

```
version: '3.8'

services:
  # Start messaging broker
  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - "5673:5672"   # Cambia el puerto publicado en el host
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"

  # Start transformation worker
  strokewidthtransform:
    image: tleyden5iwx/open-ocr-preprocessor
    volumes:
      - ./scripts/:/opt/open-ocr/
    depends_on:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -preprocessor stroke-width-transform"

  # Start OCR worker
  openocrworker:
    image: tleyden5iwx/open-ocr-2
    volumes:
      - ./scripts/:/opt/open-ocr/
    depends_on:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/"

  # Start HTTP server
  openocr:
    image: tleyden5iwx/${OPEN_OCR_INSTANCE}
    volumes:
      - ./scripts/:/opt/open-ocr/
    ports:
      - "9292:9292"
    depends_on:
      - rabbitmq
      - openocrworker
      - strokewidthtransform
    command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292"
```
