### ISSUE TITLE
Node-Red yaml

### ISSUE THREAD

**Issue by cirinho** [oriondesign2015/SetupOrion#56]
Bom dia,

Segue uma contribuição da imagem do node-red ao passo que desde já fica a solicitação da inclusão no instalador.
O node-red parece o n8n e é bastante usado em automação residencial e afins, acredito q seria útil essa stack. Segue o modelo.

```
version: '3.7'
services:
  nodered:
    # container_name: nodered
    image: nodered/node-red:latest-22
    ports:
      - 1880:1880
    networks:
      - traefik-public
    volumes:
      - node_red_data:/data     
    environment:
      - TZ=America/Bahia
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  node_red_data:
    external: true
    name: node_red_data

networks:
  traefik-public:
    external: true
    name: traefik-public
```
